### ISSUE TITLE
What're the differences among these `isort` relevant packages: `py-isort`, `isortify`, and `python-isort`?

### ISSUE THREAD

**Issue by hongyi-zhao** [wyuenho/emacs-python-isort#2]
I noticed there are three [isort relevant packges](https://melpa.org/#/?q=isort&sort=downloads&asc=false): [`py-isort`](https://github.com/paetzke/py-isort.el), [`isortify`](https://github.com/pythonic-emacs/isortify), and [`python-isort`](https://github.com/wyuenho/emacs-python-isort). It seems that all these packages are designed to do the similar work: Use `isort` to sort the imports in a Python buffer. Considering that there are already similar projects, why do you still decide to create this new project? So, I want to know what're the differences among these `isort` relevant packages: `py-isort`, `isortify`, and `python-isort`.

Regards,
HZ

**Comment by wyuenho** [comment]
`isortify` is unmaintained and the command and arguments are hardcoded, `py-isort` is maintained but the command and config file search mechanism cannot be easily changed. Generally a python project have its own `isort` version and path in a `virtualenv` and the isort config situated in a number of possible files like `pyproject.toml`, `.pre-commit-config`, `.isort.cfg` etc. While there are a number of virtualenv packages for emacs to mess with `exec-path`, none of them are great due to the many different kinds of tools that creates virtualenvs in many different places. This means python tools packages should completely leave providing the binary, arguments and lookup of the config file to the user, which is what this package provides, thanks to reformatter.

**Comment by hongyi-zhao** [comment]
Today, I noticed another wonderful project [autoimport](https://github.com/lyz-code/autoimport/), which has the following [features](https://lyz-code.github.io/autoimport/#features):

- Add missing imports
- Remove unused import statements
- Moving the imports to the top

It would be very convenient if this project could combine autoimport into its currently workflow as a step.

**Comment by wyuenho** [comment]
Nah, these things are best left to LSP.
